[package]
name = "lls"
version = "0.1.0"
edition = "2021"

[[bin]]
name="lls"

[profile.release]
lto=true
debug-assertions=false
opt-level=3
codegen-units=1

[dependencies]
clap = { version = "4.5.23", features = [ "derive" ]}
console = "0.15.10"
uzers = "0.12.1"
